#!/bin/bash

source Project

TARGET=$BUILDDIR/$PROJECTNAME

OBJS=
TXT2=
for f in $(find src | sort)
do
	if [[ $f == *.cpp ]]
	then
		OBJ=$BUILDDIR/$(echo $f | awk '{gsub(/.*\//,"",$1);gsub(/\.cpp$/,"",$1);print}').o
		OBJS="$OBJS $OBJ"
		TXT2="$TXT2$OBJ : $f\n"
		TXT2="$TXT2\t$GPP -o $OBJ $COMPFLAGS -c $f""\n\n"
		#CPPFILES="$CPPFILES $OBJ"
	fi
done

> Makefile
echo -e ".PHONY: all, clean\n" >> Makefile
echo -e "all : $TARGET\n" >> Makefile
echo -e "rebuild : clean all\n" >> Makefile
echo -e "clean :\n\t-rm $BUILDDIR/*\n" >> Makefile
echo -e "$TARGET : $OBJS" >> Makefile
echo -e "\t$GPP -o $TARGET $LINKFLAGS $OBJS $LIBFLAGS\n" >> Makefile
echo -e $TXT2 >> Makefile
