#!/bin/bash

function deps
{
	local src found incs inc
	src=$1
	found=$2

	incs=$(gawk '/#include ".*"/{gsub(/#include/,"");gsub(/"/,"");print}' $src)
	
	for inc in $incs
	do
		inc="src/$inc"
		if [[ $found != *$inc* ]]
		then
			found="$found $inc"
			found=$(deps $inc "$found")
		fi
	done
	
	echo $found
}

function objectrule
{
	local srcname objname objdeps
	srcname=$1
	objname=$2
	
	objdeps=$(deps $srcname)
	
	echo -n "$objname : $objdeps\n"
	echo -n "\t$GPP -o $objname $COMPFLAGS -c $srcname\n"
	echo -n "\n"
}

source Project

target=$BUILDDIR/$PROJECTNAME
objects=""
objrules=""

for f in $(find $SRCDIR | sort)
do
	if [[ $f == *.cpp ]]
	then
		objname=$BUILDDIR/$(echo $f | awk '{gsub(/.*\//,"",$1);gsub(/\.cpp$/,"",$1);print}').o
		objects="$objects $objname"
		objrules="$objrules$(objectrule $f $objname)"
	fi
done

> Makefile
echo -e ".PHONY: all, clean\n" >> Makefile
echo -e "all : $target\n" >> Makefile
echo -e "rebuild : clean all\n" >> Makefile
echo -e "clean :\n\t-rm $BUILDDIR/*\n" >> Makefile
echo -e "$target : $objects" >> Makefile
echo -e "\t$GPP -o $target $LINKFLAGS $objects $LIBFLAGS\n" >> Makefile
echo -e $objrules >> Makefile
